spring.application.name=QCecuring
#spring.security.user.name=admin
#spring.security.user.password=password123
#spring.security.user.roles=USER

spring.data.mongodb.uri=mongodb://localhost:27017/taskmanager
